name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Slack notification
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Akbar # Optional.
        SLACK_CHANNEL: general # Optional.
        SLACK_OVERRIDE_MESSAGE: 'Everything is Awesome!' # Optional.
      uses: Ilshidur/action-slack@master
      with:
        args: 'A new commit has been pushed.'

